version: 2.1

orbs:
  # Get easier access to the Windows machine executor.
  win: "circleci/windows@4.1.1"

jobs:
  build-wheel:
    docker:
      - image: "cimg/python:3.10"

    steps:
      - "checkout"
      - run:
          name: "Build Wheel"
          command: |
            python -m pip install build
            python -m build
      - store_artifacts:
          path: "./dist/"
      - persist_to_workspace:
          root: "./dist/"
          paths:
            - "*"

  pypi-upload:
    parameters:
      repository:
        type: "string"

    docker:
      - image: "cimg/python:3.10"

    environment:
      TWINE_REPOSITORY: "<< parameters.repository >>"
      TWINE_USERNAME: "__token__"

    steps:
      - attach_workspace:
          at: "release-workspace"

      - run:
          name: "Upload Wheel"
          command: |
            set -eux -o pipefail

            if [ "<< parameters.repository >>" = "testpypi" ]; then
              if [ -v TESTPYPI_API_TOKEN ]; then
                export TWINE_PASSWORD="${TESTPYPI_API_TOKEN}"
              fi
            elif [ "<< parameters.repository >>" = "pypi" ]; then
              if [ -v PYPI_API_TOKEN ]; then
                export TWINE_PASSWORD="${PYPI_API_TOKEN}"
              fi
            else
              echo "Unknown repository: << parameters.repository >>"
              exit 1
            fi

            if [ -v TWINE_PASSWORD ]; then
              python -m pip install twine
              python -m twine upload --non-interactive release-workspace/*
            else
              # If we're building a from a forked repository then we're
              # allowed to not have the credentials (but it's als fine of the
              # owner of the fork supplied their own).
              #
              # https://circleci.com/docs/built-in-environment-variables/ says
              # about `CIRCLE_PR_REPONAME`:
              #
              #   The name of the GitHub or Bitbucket repository where the
              #   pull request was created. Only available on forked PRs.
              #
              # So if it is not set then we should have had credentials and we
              # fail if we get here.
              if ! [ -v CIRCLE_PR_REPONAME ]; then
                echo "Required credentials (<<parameters.repository>>) are missing."
                exit 1
              fi
            fi

  tests:
    parameters:
      image-base:
        type: "string"
      python-version:
        type: "string"
      twisted-version:
        type: "string"

    docker:
      - image: "<< parameters.image-base >>:<< parameters.python-version >>"

    steps:
      - "checkout"
      - run:
          name: "Setup Test Environment"
          command: |
            python -m pip install coverage coveralls .[test]

            case << parameters.twisted-version >> in
              current) TW="Twisted" ;;
              trunk)   TW="git+https://github.com/twisted/twisted.git" ;;
              *)       TW="Twisted==<< parameters.twisted-version >>" ;;
            esac
            python -m pip install --upgrade "$TW"

      - run:
          name: "Run Tests"
          command: |

            python -m coverage run --source=txi2p --omit=*/_version.py,*test* -m twisted.trial txi2p
            python run_coveralls.py


workflows:
  version: 2

  release:
    jobs:
      - "build-wheel":
          filters:
            tags:
              only: "/^\\d+\\.\\d+\\.\\d+$/"
            branches:
              ignore: "/.*/"
      - "pypi-upload":
          filters:
            tags:
              only: "/^\\d+\\.\\d+\\.\\d+$/"
            branches:
              ignore: "/.*/"
          repository: "pypi"
          requires:
            - "build-wheel"

  tests:
    jobs:
      - "build-wheel"
      - "pypi-upload":
          repository: "testpypi"
          requires:
            - "build-wheel"

      - "tests":
          matrix:
            parameters:
              image-base:
                - "cimg/python"

              python-version:
                - "3.7"
                - "3.8"
                - "3.9"
                - "3.10"

              twisted-version:
                - "trunk"
                - "current"
                - "22.2.0"
                - "19.2.1"

      - "tests":
          matrix:
            parameters:
              image-base:
                - "pypy"

              python-version:
                - "3.7"
                - "3.8"
                - "3.9"

              twisted-version:
                - "trunk"
                - "current"
                - "22.2.0"
                - "19.2.1"

      - "tests":
          matrix:
            parameters:
              image-base:
                - "pypy"
                - "cimg/python"

              python-version:
                - "2.7"

              twisted-version:
                - "20.3.0"
